pose_filter:
  ros__parameters:
    
    butterworth_filter:
      sampling_rate: 10.0
      cutoff_frequency: 1.0

    slerp_filter:
      n_samples: 30

    publishers:
      aruco_pose_filter_measures_prefix: /target_tracking/camera_to_marker_transform/filter/marker_

    subscribers:
      aruco_pose_raw_measures_prefix: /target_tracking/camera_to_marker_transform/marker_
      aruco_presence_prefix: /target_tracking/camera_to_marker_presence/marker_

    frames: 
      camera: wrist_camera_link
      stable_link_prefix: filtered_marker_


